### PR TITLE
Php bb 3.1

### PR DESCRIPTION
**Pull request by zubanongs**

### CODE REVIEW

**Comment by TheZoker** [comment]
@zubanongs What exactly are you trying to do?

**Comment by zubanongs** [comment]
I'm not quite figured out how to download the style to test phpBB3.1

**Comment by zubanongs** [comment]
My English is poor. Sorry

**Comment by TheZoker** [comment]
No problem, this was the wrong button ;)
You can download it here: https://github.com/ComBoot/ComBoot-3.1

Button is here:

img_2016 01 29_17h38m23s_004_

**Comment by zubanongs** [comment]
thank you

**Comment by zubanongs** [comment]
page not found (404)

**Comment by zubanongs** [comment]
found. thans

**Pull request closed without merging**
